# Generated by Django 4.1.2 on 2022-10-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('data_validade', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('empregado', models.BooleanField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('salario', models.FloatField()),
                ('numero', models.CharField(max_length=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta', to='client.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('estado', models.CharField(max_length=2)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='client.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='client.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favoritos', to='client.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('data_pagamento', models.DateField()),
                ('data_pago', models.DateField()),
                ('id_cartoes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='client.cartoes')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='client.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('juros', models.FloatField()),
                ('validade', models.DateField()),
                ('condicao', models.BooleanField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo', to='client.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos', to='client.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cartoes',
            name='id_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='client.conta'),
        ),
    ]
